### ISSUE TITLE
api调用ts类型不兼容

### ISSUE THREAD

**Issue by f5l5y5** [ywanzhou/vue3-template#11]
1. 升级axios版本，接口拦截的ts定义不兼容
![image](https://user-images.githubusercontent.com/27725420/219567782-86b02f63-9ec1-4c1c-a5fa-8ee3c03441fa.png)

**Comment by ywanzhou** [comment]
可以拉一下代码，现在应该没问题了

**Comment by f5l5y5** [comment]
给你提了个pr，你看看行不行
